require 'tests.testarbitrate'
require 'tests.testbittrex'
require 'tests.testcraptsy'
require 'tests.testlogger'
require 'tests.testmintpal'
require 'tests.testpoloniex'
require 'tests.testretrywrap'
